name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Generate snake animation"
          add: "output/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
